---
- hosts: 80.78.244.214
  become: true
  tasks:

  - name: Creates directory "custom_prosody_plugins"
    file:
      path: /home/Jenkins/
      state: directory

  - name: 
      file: 
       path: /usr/jenkins.txt
       state: touch
       owner: root
       group: root
       mode: 0600
